### ISSUE TITLE
可以加您微信吗

### ISSUE THREAD

**Issue by liuwangbless** [linyehui/sonic#7]
可以加您微信吗，我是搞移动开发的，最近在学C++，您的代码对我有很大帮助！

**Comment by linyehui** [comment]
正常来说邮件我回复的会跟及时 :)

邮件地址:
echo qwertyuwitotepasdwqifgs | tr qeryuoasdfgipwt lnyhudgmaco.@ie

**Comment by liuwangbless** [comment]
那个问题解决了，是CoreAudioTypes.h文件中AudioBuffer里面的两个变量的问题mNumberChannels和mDataByteSize两个变量类型错误。可以加你微信吗？我是搞iOS开发的，最近在看C++和javascript。

**Comment by liuwangbless** [comment]
关键看不太懂邮件地址啊？echo qwertyuwitotepasdwqifgs | tr qeryuoasdfgipwt lnyhudgmaco.@ie是啥邮件地址啊？想膜拜一下C++大神！

**Comment by liuwangbless** [comment]
超声波模式下传输距离和质量没办法保证，有啥好的办法解决吗？音频这块完全不懂怎么降噪。

**Comment by linyehui** [comment]
linyehui.eden@gmail.com

echo是命令，你复制上面那行在terminal下执行，就能看到我上面的邮件地址了

**Comment by linyehui** [comment]
音频传输我也不是特别懂，目前看来其实不太适合拿来传输大量的数据，降噪是大问题不好解决

**Comment by alexlo2000** [comment]
@linyehui 频率识别准确率还是很高的，都能准确检测出来了。调用高频那噪声影响就很小了。就是在结合rscode解码的时候出了问题。正好这里我也看不懂。不知道 @linyehui 对这个有木有心得。

**Comment by linyehui** [comment]
算法思路可以参考:[声波传输技术简介](http://rest.sinaapp.com/?a=technology)，然后再结合源码看应该可以看个7、8层，涉及到的技术关键字上面这篇文章里都有提到，可以自己再搜索、深入了解下。

RS codes简单来说就是通过数据冗余来对抗噪声，但是如果噪声太大那么RS还是一样会失效。

降噪的问题，目前的代码其实是没有处理的，全凭手机的双MIC降噪，这块是这个代码最大的缺陷;
实际的效果是在安静的办公室识别效果还勉强可以，但是到来吵闹一点的户外环境识别率就很低。

我自己也是之前完全不懂数字模拟这块的算法，了解后勉强能看得懂，心得就没啥，有具体的问题可能可以一起探讨下。

另外你们也可以问下这个算法的原作者:  @[WaveTrans](https://github.com/CloudSide/WaveTrans)，他对这个算法应该更了解。
